/*
 * Centrify Vault REST API
 *
 * Vault REST API specification 
 *
 * API version: 1.0
 * Contact: support@centrify.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package secretinternal

import (
	"encoding/json"
	"reflect"
	"strings"
)

// SecretBagPatchable struct for SecretBagPatchable
type SecretBagPatchable struct {
	SecretPatchable
	// The privileged data in a secret bag. Required for vault and modify operations.
	Data map[string]string `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _SecretBagPatchable SecretBagPatchable

// NewSecretBagPatchable instantiates a new SecretBagPatchable object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretBagPatchable(data map[string]string, type_ Secrettypes) *SecretBagPatchable {
	this := SecretBagPatchable{}
	this.Type = type_
	this.Data = data
	return &this
}

// NewSecretBagPatchableWithDefaults instantiates a new SecretBagPatchable object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretBagPatchableWithDefaults() *SecretBagPatchable {
	this := SecretBagPatchable{}
	return &this
}

// GetData returns the Data field value
func (o *SecretBagPatchable) GetData() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SecretBagPatchable) GetDataOk() (*map[string]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SecretBagPatchable) SetData(v map[string]string) {
	o.Data = v
}

func (o SecretBagPatchable) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedSecretPatchable, errSecretPatchable := json.Marshal(o.SecretPatchable)
	if errSecretPatchable != nil {
		return []byte{}, errSecretPatchable
	}
	errSecretPatchable = json.Unmarshal([]byte(serializedSecretPatchable), &toSerialize)
	if errSecretPatchable != nil {
		return []byte{}, errSecretPatchable
	}
	if true {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *SecretBagPatchable) UnmarshalJSON(bytes []byte) (err error) {
	type SecretBagPatchableWithoutEmbeddedStruct struct {
		// The privileged data in a secret bag. Required for vault and modify operations.
		Data map[string]string `json:"data"`
	}

	varSecretBagPatchableWithoutEmbeddedStruct := SecretBagPatchableWithoutEmbeddedStruct{}

	err = json.Unmarshal(bytes, &varSecretBagPatchableWithoutEmbeddedStruct)
	if err == nil {
		varSecretBagPatchable := _SecretBagPatchable{}
		varSecretBagPatchable.Data = varSecretBagPatchableWithoutEmbeddedStruct.Data
		*o = SecretBagPatchable(varSecretBagPatchable)
	} else {
		return err
	}

	varSecretBagPatchable := _SecretBagPatchable{}

	err = json.Unmarshal(bytes, &varSecretBagPatchable)
	if err == nil {
		o.SecretPatchable = varSecretBagPatchable.SecretPatchable
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "data")

		// remove fields from embedded structs
		reflectSecretPatchable := reflect.ValueOf(o.SecretPatchable)
		for i := 0; i < reflectSecretPatchable.Type().NumField(); i++ {
			t := reflectSecretPatchable.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSecretBagPatchable struct {
	value *SecretBagPatchable
	isSet bool
}

func (v NullableSecretBagPatchable) Get() *SecretBagPatchable {
	return v.value
}

func (v *NullableSecretBagPatchable) Set(val *SecretBagPatchable) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretBagPatchable) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretBagPatchable) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretBagPatchable(val *SecretBagPatchable) *NullableSecretBagPatchable {
	return &NullableSecretBagPatchable{value: val, isSet: true}
}

func (v NullableSecretBagPatchable) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretBagPatchable) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


