/*
 * Centrify Vault REST API
 *
 * Vault REST API specification 
 *
 * API version: 1.0
 * Contact: support@centrify.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package secretinternal

import (
	"encoding/json"
	"reflect"
	"strings"
)

// SecretFolderWritable struct for SecretFolderWritable
type SecretFolderWritable struct {
	SecretWritable
	AdditionalProperties map[string]interface{}
}

type _SecretFolderWritable SecretFolderWritable

// NewSecretFolderWritable instantiates a new SecretFolderWritable object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretFolderWritable(type_ Secrettypes, name string) *SecretFolderWritable {
	this := SecretFolderWritable{}
	this.Type = type_
	this.Name = name
	return &this
}

// NewSecretFolderWritableWithDefaults instantiates a new SecretFolderWritable object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretFolderWritableWithDefaults() *SecretFolderWritable {
	this := SecretFolderWritable{}
	return &this
}

func (o SecretFolderWritable) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedSecretWritable, errSecretWritable := json.Marshal(o.SecretWritable)
	if errSecretWritable != nil {
		return []byte{}, errSecretWritable
	}
	errSecretWritable = json.Unmarshal([]byte(serializedSecretWritable), &toSerialize)
	if errSecretWritable != nil {
		return []byte{}, errSecretWritable
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *SecretFolderWritable) UnmarshalJSON(bytes []byte) (err error) {
	type SecretFolderWritableWithoutEmbeddedStruct struct {
	}

	varSecretFolderWritableWithoutEmbeddedStruct := SecretFolderWritableWithoutEmbeddedStruct{}

	err = json.Unmarshal(bytes, &varSecretFolderWritableWithoutEmbeddedStruct)
	if err == nil {
		varSecretFolderWritable := _SecretFolderWritable{}
		*o = SecretFolderWritable(varSecretFolderWritable)
	} else {
		return err
	}

	varSecretFolderWritable := _SecretFolderWritable{}

	err = json.Unmarshal(bytes, &varSecretFolderWritable)
	if err == nil {
		o.SecretWritable = varSecretFolderWritable.SecretWritable
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {

		// remove fields from embedded structs
		reflectSecretWritable := reflect.ValueOf(o.SecretWritable)
		for i := 0; i < reflectSecretWritable.Type().NumField(); i++ {
			t := reflectSecretWritable.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSecretFolderWritable struct {
	value *SecretFolderWritable
	isSet bool
}

func (v NullableSecretFolderWritable) Get() *SecretFolderWritable {
	return v.value
}

func (v *NullableSecretFolderWritable) Set(val *SecretFolderWritable) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretFolderWritable) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretFolderWritable) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretFolderWritable(val *SecretFolderWritable) *NullableSecretFolderWritable {
	return &NullableSecretFolderWritable{value: val, isSet: true}
}

func (v NullableSecretFolderWritable) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretFolderWritable) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


