/*
 * Centrify Vault REST API
 *
 * Vault REST API specification 
 *
 * API version: 1.0
 * Contact: support@centrify.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package secretinternal

import (
	"encoding/json"
	"reflect"
	"strings"
)

// SecretBagWritable Useful model for determining what attributes of a secret bag are writable.  Note that semantics of POST / PUT / PATCH apply differently. 
type SecretBagWritable struct {
	SecretWritable
	// The privileged data in a secret bag. Required for vault and modify operations.
	Data map[string]string `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _SecretBagWritable SecretBagWritable

// NewSecretBagWritable instantiates a new SecretBagWritable object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretBagWritable(data map[string]string, type_ Secrettypes, name string) *SecretBagWritable {
	this := SecretBagWritable{}
	this.Type = type_
	this.Name = name
	this.Data = data
	return &this
}

// NewSecretBagWritableWithDefaults instantiates a new SecretBagWritable object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretBagWritableWithDefaults() *SecretBagWritable {
	this := SecretBagWritable{}
	return &this
}

// GetData returns the Data field value
func (o *SecretBagWritable) GetData() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SecretBagWritable) GetDataOk() (*map[string]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SecretBagWritable) SetData(v map[string]string) {
	o.Data = v
}

func (o SecretBagWritable) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedSecretWritable, errSecretWritable := json.Marshal(o.SecretWritable)
	if errSecretWritable != nil {
		return []byte{}, errSecretWritable
	}
	errSecretWritable = json.Unmarshal([]byte(serializedSecretWritable), &toSerialize)
	if errSecretWritable != nil {
		return []byte{}, errSecretWritable
	}
	if true {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *SecretBagWritable) UnmarshalJSON(bytes []byte) (err error) {
	type SecretBagWritableWithoutEmbeddedStruct struct {
		// The privileged data in a secret bag. Required for vault and modify operations.
		Data map[string]string `json:"data"`
	}

	varSecretBagWritableWithoutEmbeddedStruct := SecretBagWritableWithoutEmbeddedStruct{}

	err = json.Unmarshal(bytes, &varSecretBagWritableWithoutEmbeddedStruct)
	if err == nil {
		varSecretBagWritable := _SecretBagWritable{}
		varSecretBagWritable.Data = varSecretBagWritableWithoutEmbeddedStruct.Data
		*o = SecretBagWritable(varSecretBagWritable)
	} else {
		return err
	}

	varSecretBagWritable := _SecretBagWritable{}

	err = json.Unmarshal(bytes, &varSecretBagWritable)
	if err == nil {
		o.SecretWritable = varSecretBagWritable.SecretWritable
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "data")

		// remove fields from embedded structs
		reflectSecretWritable := reflect.ValueOf(o.SecretWritable)
		for i := 0; i < reflectSecretWritable.Type().NumField(); i++ {
			t := reflectSecretWritable.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSecretBagWritable struct {
	value *SecretBagWritable
	isSet bool
}

func (v NullableSecretBagWritable) Get() *SecretBagWritable {
	return v.value
}

func (v *NullableSecretBagWritable) Set(val *SecretBagWritable) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretBagWritable) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretBagWritable) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretBagWritable(val *SecretBagWritable) *NullableSecretBagWritable {
	return &NullableSecretBagWritable{value: val, isSet: true}
}

func (v NullableSecretBagWritable) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretBagWritable) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


