/*
 * Centrify Vault REST API
 *
 * Vault REST API specification 
 *
 * API version: 1.0
 * Contact: support@centrify.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package secretinternal

import (
	"encoding/json"
	"reflect"
	"strings"
)

// PrivilegedBagData struct for PrivilegedBagData
type PrivilegedBagData struct {
	PrivilegedData
	// The privileged data in a secret bag. Required for vault and modify operations.
	Data map[string]string `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _PrivilegedBagData PrivilegedBagData

// NewPrivilegedBagData instantiates a new PrivilegedBagData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivilegedBagData(data map[string]string, type_ Secrettypes) *PrivilegedBagData {
	this := PrivilegedBagData{}
	this.Type = type_
	this.Data = data
	return &this
}

// NewPrivilegedBagDataWithDefaults instantiates a new PrivilegedBagData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivilegedBagDataWithDefaults() *PrivilegedBagData {
	this := PrivilegedBagData{}
	return &this
}

// GetData returns the Data field value
func (o *PrivilegedBagData) GetData() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PrivilegedBagData) GetDataOk() (*map[string]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *PrivilegedBagData) SetData(v map[string]string) {
	o.Data = v
}

func (o PrivilegedBagData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedPrivilegedData, errPrivilegedData := json.Marshal(o.PrivilegedData)
	if errPrivilegedData != nil {
		return []byte{}, errPrivilegedData
	}
	errPrivilegedData = json.Unmarshal([]byte(serializedPrivilegedData), &toSerialize)
	if errPrivilegedData != nil {
		return []byte{}, errPrivilegedData
	}
	if true {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *PrivilegedBagData) UnmarshalJSON(bytes []byte) (err error) {
	type PrivilegedBagDataWithoutEmbeddedStruct struct {
		// The privileged data in a secret bag. Required for vault and modify operations.
		Data map[string]string `json:"data"`
	}

	varPrivilegedBagDataWithoutEmbeddedStruct := PrivilegedBagDataWithoutEmbeddedStruct{}

	err = json.Unmarshal(bytes, &varPrivilegedBagDataWithoutEmbeddedStruct)
	if err == nil {
		varPrivilegedBagData := _PrivilegedBagData{}
		varPrivilegedBagData.Data = varPrivilegedBagDataWithoutEmbeddedStruct.Data
		*o = PrivilegedBagData(varPrivilegedBagData)
	} else {
		return err
	}

	varPrivilegedBagData := _PrivilegedBagData{}

	err = json.Unmarshal(bytes, &varPrivilegedBagData)
	if err == nil {
		o.PrivilegedData = varPrivilegedBagData.PrivilegedData
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "data")

		// remove fields from embedded structs
		reflectPrivilegedData := reflect.ValueOf(o.PrivilegedData)
		for i := 0; i < reflectPrivilegedData.Type().NumField(); i++ {
			t := reflectPrivilegedData.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePrivilegedBagData struct {
	value *PrivilegedBagData
	isSet bool
}

func (v NullablePrivilegedBagData) Get() *PrivilegedBagData {
	return v.value
}

func (v *NullablePrivilegedBagData) Set(val *PrivilegedBagData) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivilegedBagData) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivilegedBagData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivilegedBagData(val *PrivilegedBagData) *NullablePrivilegedBagData {
	return &NullablePrivilegedBagData{value: val, isSet: true}
}

func (v NullablePrivilegedBagData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivilegedBagData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


