/*
 * Centrify Vault REST API
 *
 * Vault REST API specification 
 *
 * API version: 1.0
 * Contact: support@centrify.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package secretinternal

import (
	"encoding/json"
	"reflect"
	"strings"
)

// SecretTextPatchable struct for SecretTextPatchable
type SecretTextPatchable struct {
	SecretPatchable
	// The privileged data in a text secret. Required for vault and modify operations.
	Data string `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _SecretTextPatchable SecretTextPatchable

// NewSecretTextPatchable instantiates a new SecretTextPatchable object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretTextPatchable(data string, type_ Secrettypes) *SecretTextPatchable {
	this := SecretTextPatchable{}
	this.Type = type_
	this.Data = data
	return &this
}

// NewSecretTextPatchableWithDefaults instantiates a new SecretTextPatchable object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretTextPatchableWithDefaults() *SecretTextPatchable {
	this := SecretTextPatchable{}
	return &this
}

// GetData returns the Data field value
func (o *SecretTextPatchable) GetData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SecretTextPatchable) GetDataOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SecretTextPatchable) SetData(v string) {
	o.Data = v
}

func (o SecretTextPatchable) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedSecretPatchable, errSecretPatchable := json.Marshal(o.SecretPatchable)
	if errSecretPatchable != nil {
		return []byte{}, errSecretPatchable
	}
	errSecretPatchable = json.Unmarshal([]byte(serializedSecretPatchable), &toSerialize)
	if errSecretPatchable != nil {
		return []byte{}, errSecretPatchable
	}
	if true {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *SecretTextPatchable) UnmarshalJSON(bytes []byte) (err error) {
	type SecretTextPatchableWithoutEmbeddedStruct struct {
		// The privileged data in a text secret. Required for vault and modify operations.
		Data string `json:"data"`
	}

	varSecretTextPatchableWithoutEmbeddedStruct := SecretTextPatchableWithoutEmbeddedStruct{}

	err = json.Unmarshal(bytes, &varSecretTextPatchableWithoutEmbeddedStruct)
	if err == nil {
		varSecretTextPatchable := _SecretTextPatchable{}
		varSecretTextPatchable.Data = varSecretTextPatchableWithoutEmbeddedStruct.Data
		*o = SecretTextPatchable(varSecretTextPatchable)
	} else {
		return err
	}

	varSecretTextPatchable := _SecretTextPatchable{}

	err = json.Unmarshal(bytes, &varSecretTextPatchable)
	if err == nil {
		o.SecretPatchable = varSecretTextPatchable.SecretPatchable
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "data")

		// remove fields from embedded structs
		reflectSecretPatchable := reflect.ValueOf(o.SecretPatchable)
		for i := 0; i < reflectSecretPatchable.Type().NumField(); i++ {
			t := reflectSecretPatchable.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSecretTextPatchable struct {
	value *SecretTextPatchable
	isSet bool
}

func (v NullableSecretTextPatchable) Get() *SecretTextPatchable {
	return v.value
}

func (v *NullableSecretTextPatchable) Set(val *SecretTextPatchable) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretTextPatchable) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretTextPatchable) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretTextPatchable(val *SecretTextPatchable) *NullableSecretTextPatchable {
	return &NullableSecretTextPatchable{value: val, isSet: true}
}

func (v NullableSecretTextPatchable) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretTextPatchable) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


