name: build-platform-go-sdk

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:

  build:
    name: build-platform-go-sdk
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-latest, self-hosted]
        
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout Platform sdk
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.7

      - name: Setup
        run: |
          go mod download
          go install gotest.tools/gotestsum@latest

      - name: Test
        run: |
          gotestsum -f testname ./... >> platform-go-sdk.txt

      - name: Test output
        if: ${{ always() }}
        run: |
          cat platform-go-sdk.txt
